version: "3"

services:
  intelligence-battle-webapi:
    build:
      context: ./IntelligenceBattle.WebApi
      dockerfile: ./Dockerfile
    ports:
      - "8008:7000"
    expose:
      - "8008"
    env_file:
     - ./.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production