version: "3"

services:
  intelligence-battle-webapi:
    depends_on:
      - postgresql
    image: bitoid/intelligence-battle-service:dev
    ports:
      - "8008:7000"
    expose:
      - "8008"
    env_file:
     - ./.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
  postgresql:
    image: "postgres:12"
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
  intelligence-battle-services-game-manager:
    depends_on:
      - postgresql
    image: bitoid/intelligence-battle-service:dev
    env_file:
     - ./.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
  nginx:
    depends_on:
      - intelligence-battle-webapi
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  database-data: 
